### ISSUE TITLE
How to cite ImageScience

### ISSUE THREAD

**Issue by tischi** [fiji/imagescience#2]
@emeijering 
How could we cite ImageScience?
Is there a publication? If not, what about putting the repo to ZENODO?

**Comment by emeijering** [comment]
See the [https://imagescience.org/meijering/software/imagescience/](ImageScience) webpage for details.

**Comment by emeijering** [comment]
See the [ImageScience](https://imagescience.org/meijering/software/imagescience/) webpage for details.

**Comment by tischi** [comment]
@emeijering 
In fact, I did have a look at above web-page before, but I could not find instructions about how to cite the software... could you help us there?

**Comment by emeijering** [comment]
The precise text is up to you but it would be nice to at least include the URL so readers can easily find the software.

**Comment by tischi** [comment]
OK! Will do!
Just as an idea: one way to make a GitHub repos officially citable these days is using ZENODO, such as, e.g.: 
- Tischer, C. (2019). ElastixWrapper: Fiji plugin for 3D image registration with elastix. Zenodo. http://doi.org/10.5281/zenodo.2602549
