### ISSUE TITLE
Dealing with anisotropic data

### ISSUE THREAD

**Issue by tischi** [fiji/imagescience#3]
Dear @emeijering,

I have two questions:

1. Does the FeatureJ Hessian take the image calibration into account? My data is has an an-isotropic voxel size in 3D. If not, should I resample it isotropic?
2. Even if I resample it isotropic there of course is still more blur along the z-axis. Thus, the eigenvalues that are not ideal for Hessian based shape analysis along those lines: https://www.researchgate.net/publication/2388170_Multiscale_Vessel_Enhancement_Filtering 
What would you recommend? I was thinking of (a) deconvolution or (b) blurring in xy such that I have as much blur in xy as in z...

**Comment by emeijering** [comment]
Hi @tischi,

1. Yes, there is an option to take voxel calibration into account, see https://imagescience.org/meijering/software/featurej/hessian/ under "smoothing scale".

2. Voxel anisotropy occurs in many 3D imaging applications, and whether that is a problem depends on the resolution requirements of subsequent analyses, so it is hard to give general advice. Depending on the level of spatial detail needed for your application, you may indeed consider deconvolution or equalizing the blurring.

**Comment by tischi** [comment]
Thanks @emeijering,

I was in fact not aware of this option:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/2157566/123227690-1deb1400-d4d5-11eb-9f74-a96712fabc39.png">

And thanks for the advice, I will try deconvolution and "blur equalization".
